global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: backend
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /actuator/prometheus
    honor_labels: true
    scheme: http
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
          - /prometheus/discovered.yml
        refresh_interval: 2m