# config file version
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    access: direct
    url: http://localhost:9090
    isDefault: true
    editable: true