name: Nuke whole account
run-name: Nuke resources in the account using AWS Nuke

on:
  workflow_dispatch:
    inputs:
      hubEnv:
        description: Select target hub and stage
        required: true
        type: choice
        options:
          - 'BACKEND_EMEA_TEST'
      technicalUser:
        description: Name of the technical user
        required: true
        type: string

jobs:
  properties:
    uses: ./.github/workflows/datacenterMap.yml
    with:
      hubEnv: ${{ inputs.hubEnv }}
    secrets: inherit

  nuke:
    runs-on: ubuntu-latest
    needs: properties
    env:
      AWS_ACCOUNT: ${{ needs.properties.outputs.AWS_ACCOUNT }}
      AWS_PROFILE: ${{ needs.properties.outputs.PROFILE }}
      AWS_KEY:  ${{ secrets[format('{0}_AWS_KEY', inputs.hubEnv)] }}
      AWS_SECRET: ${{ secrets[format('{0}_AWS_SECRET', inputs.hubEnv)] }}
      AWS_REGION: ${{ needs.properties.outputs.REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Configure AWS profile
        run: |
          mkdir -p ~/.aws
          echo "[${{ env.AWS_PROFILE }}]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ env.AWS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ env.AWS_SECRET }}" >> ~/.aws/credentials

      - name: Setup config
        run: |
          sed -i 's/{REGION}/${{ env.AWS_REGION }}/g' nukeConfig.yml
          sed -i 's/{TECHNICAL_USER}/${{ inputs.technicalUser }}/g' nukeConfig.yml
          sed -i 's/{ACCOUNT_ID}/${{ env.AWS_ACCOUNT }}/g' nukeConfig.yml

      - name: Configure alias
        run: |
          aws iam create-account-alias --account-alias sandbox-${{ inputs.technicalUser }} --profile ${{ env.AWS_PROFILE }} || echo "Alias already exists"

      - name: Install Nuke
        run: |
          # Download aws-nuke binary
          wget https://github.com/rebuy-de/aws-nuke/releases/download/v2.25.0/aws-nuke-v2.25.0-linux-amd64.tar.gz

          # Unzip
          tar -xvzf aws-nuke-v2.25.0-linux-amd64.tar.gz
          
          # Make the binary executable
          chmod u+x aws-nuke-v2.25.0-linux-amd64
          sudo mv aws-nuke-v2.25.0-linux-amd64 /usr/local/bin/aws-nuke

          # Test the installation
          aws-nuke --help

      - name: Run Nuke
        run: |
          ALIAS=sandbox-${{ inputs.technicalUser }}
          printf "$ALIAS\n$ALIAS" | \
          aws-nuke \
          --config /home/runner/work/awstraining-backend/awstraining-backend/nukeConfig.yml \
          --access-key-id ${{ env.AWS_KEY }} \
          --secret-access-key ${{ env.AWS_SECRET }} \
          --no-dry-run
